### ISSUE TITLE
Same issue, rename failed

### ISSUE THREAD

**Issue by advplyr** [jamesbontempo/njodb#11]
First hour of using the new version on Windows the rename failed and I lost the user data.

The writer did not throw any errors, but we did learn that the tmp file is being created.

[2021-11-03T21:59:43.481Z] ERROR: [DB] Update entity user Failed: Error: ENOENT: no such file or directory, rename 'C:\audiobookshelf\config\users\tmp\data.0.json.1635976783472.tmp' -> 'C:\audiobookshelf\config\users\data\data.0.json'

Tmp file was created. Those other .old files are older failed renames, and likely their corresponding tmp file.
![image](https://user-images.githubusercontent.com/67830747/140200914-9a4598dd-853f-4212-b812-44e856312e80.png)

I know I have come across some strange issues with node fs in windows regarding file handles remaining open. I found this project:
https://github.com/isaacs/node-graceful-fs
It seems this is a known problem because graceful fs solved for it by retrying the rename in the case it fails:
```On Windows, it retries renaming a file for up to one second if EACCESS or EPERM error occurs, likely because antivirus software has locked the directory.```

Not very elegant unfortunately.

**Comment by advplyr** [comment]
Just happened again, but I did not restart the server so the data.0.json wasn't re-created.

This is as expected but I just wanted to make sure we are on the same page.
I can recover the data right now before starting the server but renaming `data.0.json.old` to `data.0.json`

![image](https://user-images.githubusercontent.com/67830747/140233305-46ee0e7f-6544-4815-ba46-1b9af8144544.png)

**Comment by advplyr** [comment]
I went to write a function to check and fix the db files on ENOENT errors on my end, but after you removed the try catch the lockfile is not getting released.
As far as I could tell I can't release the lock and deleting the .lock directory results in proper-lockfile throwing an error.

**Comment by jamesbontempo** [comment]
Well, that's a bummer :( I'll take a look at graceful-fs & see if I can implement something similar, or maybe even just use it as a drop-in replacement for Node's fs. I think proper-lockfile might actually use graceful-fs "under the hood" (or at that it can be configured to do so). Either way, I'll let you know when I have something for you to try out. Thanks again for all of your help & patience w/this!

**Comment by advplyr** [comment]
I forgot to mention another alternative. I have been using fs-extra for a while and find it incredibly useful. It is a drop-in replacement to fs so just changing `fs` to `fs-extra` is all that is needed, but it does have a few nice helper functions. It uses graceful-fs as well.

https://www.npmjs.com/package/fs-extra

Something to consider when you are looking into it.

**Comment by jamesbontempo** [comment]
Oh! I'm just seeing your message & I just pushed a new version of 'njodb` that uses `graceful-fs`. Maybe the next one will use `fs-extra` :)

This latest `njodb` has a bunch of code for checking & handling a range of file system-related issues, including attempting to revert "old" JSON data files if the swap for a "tmp" file isn't successful. It also has a bunch of code for handling lock-related things, too.

I've done several rounds of testing with 10 concurrent users, issuing multiple inserts of 1000 records while also selecting, updating, & deleting data in a database with over 100,000 records, and I haven't seen any unexpected issues crop up. I say "unexpected" because one recurring error is, _I think_, related to `proper-lockfile` trying to update locks that have already been released (it does its checking via a `setTimeout()` which I suspect sometimes winds up being triggered after the lock no longer exists).

I'm hoping that these updates take care of the various problems you've been running up against 🤞 If so, feel free to close out this issue (I'm going to leave it open until you've had a chance to do some testing). If not, it's back to the drawing board...

**Comment by advplyr** [comment]
I have been testing for a few hours now and trying to track down another error.

https://github.com/jamesbontempo/njodb/blob/master/lib/njodb.js#L504

It turned out that line is throwing the exception:
ENOENT: no such file or directory, unlink 'C:\audiobookshelf\config\audiobooks\tmp\data.4.json.1636236380425.tmp'

This is when a store has no updates, so no data is lost here, but the lock file is never released because of the exception.

I don't know why these tmp files are still throwing ENOENT when they exist.. I still haven't been able to track that down. When the lock remains open though the database can't be updated, so if we can catch that exception in the meantime that would be great.

These file system issues with node are exhausting!

**Comment by jamesbontempo** [comment]
Ack! I forgot to update those two calls 😱 I've just pushed a version that will print `unlink` issues for the "tmp" files to the error console but _shouldn't_ kill the process & so should allow the lock to be released🤞 And yeah, kinda exhausting ;) But I think we're almost there...

**Comment by jamesbontempo** [comment]
FYI, I just pushed a version w/an additional minor tweak: if the replaceFile call fails for an update or delete, the `updated` or `deleted` property of the `Result` object gets set to 0. I'm thinking that in a future version it would probably be helpful to provide some information about what, specifically, didn't get updated or deleted, maybe somewhere in the `errors` array...

**Comment by advplyr** [comment]
I've got a few hours on testing the latest version and so far so good. The rename error gets shown but it doesn't break anything else. Hopefully in time I can get more info on why these tmp files aren't able to be renamed.

I see the `updated` is returning 0 but I have no way of knowing if this is 0 due to an error or 0 because there was just nothing to update. If it is 0 due to an error I could add some extra code to retry the update.

Great work so far, thank you!

**Comment by jamesbontempo** [comment]
Hey! Sorry I've been MIA for a bit. I totally hear you & I'm going to take a look right now at how to potentially return some detailed info about file system issues when updating or deleting data.

**Comment by jamesbontempo** [comment]
Alright, I just pushed a new version 👍 

If an update or delete fails because of some file system issue the `errors` array in the `results` object will now contain the records that were not able to be updated or deleted. One word of caution: this array can also contain records in the db that are problematic (i.e., not parseable using `JSON.parse()`).

Because the `errors` array now contains different types of objects, you may need to check each one to make sure which type it is before doing anything with it. For example, if you're interested in parsing-related errors, while looping through the objects you can check if one contains the `error` property. Of course, it's possible that you're data _also_ contains an `error` property, so that may not be a fail-safe way of doing things. Perhaps the best approach would be to check that the object in the array has the same "shape" as your data, and that would tell you that it's a record that couldn't be updated/deleted.

I hope that makes some sense! And I hope it will provide what you need to (at least attempt to) recover from file system-related issues.

BTW, I don't have an easy way to test these updates, so I'm sort of relying on you to help determine if they work 🙏

**Comment by jamesbontempo** [comment]
Hey @advplyr :) How are things going since the last update? Well, I hope! If so, I'll go ahead and close this issue out. If not, let me know what's up & we can figure out what to do next...

**Comment by advplyr** [comment]
Hey @jamesbontempo
The same error still exists on Windows (https://github.com/jamesbontempo/njodb/issues/11#issuecomment-962517657), but since you have added the exception catch it hasn't forced me to debug.
It is still quite frequent, maybe 1 of every 20 db updates.

```
[Error: ENOENT: no such file or directory, unlink 'C:\audiobookshelf\config\users\tmp\data.1.json.1641642539298.tmp'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'unlink',
  path: 'C:\\audiobookshelf\\config\\users\\tmp\\data.1.json.1641642539298.tmp'
}
[2022-01-08T11:48:59.357Z] DEBUG: [DB] Updated user: 1
```

Because these tmp files don't get removed, I have about 200 tmp files in the tmp folder.

**Comment by jamesbontempo** [comment]
Hmmm... That is odd that `updated` is 0. There are two situations where this could be the case: 1) the `selecter` function doesn't find any matching records to update, or 2) the `updater` function fails.

I've just pushed a new version that adds a `selected` property to the update `results` object. I'm curious to know if `selected` and `updated` match. If they don't then that might help zero in on where things are going awry.

Could you update `njodb`, run things for a while, check both `selected` & `updated` when things fail, then let me know what you find?

**Comment by advplyr** [comment]
Will do, thanks for the update.

**Comment by advplyr** [comment]
Updated and selected match

```
[Error: ENOENT: no such file or directory, unlink 'C:\audiobookshelf\config\users\tmp\data.1.json.1643064656006.tmp'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'unlink',
  path: 'C:\\audiobookshelf\\config\\users\\tmp\\data.1.json.1643064656006.tmp'
}
[2022-01-24T22:50:56.070Z] DEBUG: [DB] Updated user: 1 | Selected: 1
```

**Comment by jamesbontempo** [comment]
Hmmm... Do you have any ENOENT error from when `updated` is 0? If so, is `selected` also 0?

**Comment by jamesbontempo** [comment]
What's odd about your last error there is that a "tmp" file should only ever get deleted if there are no updates (i.e., if `updated` is zero).

When there _are_ updates, the data file gets an "old" extension and the "tmp" file gets renamed (not unlinked) so that it replaces the data file, and the "old" data file gets deleted (i.e., unlinked). If the renaming fails, then the "old" file is reverted back to the original and the "tmp" file is ignored (but it should be deleted... whoops!).

So, an "ENOENT: no such file or directory" error about an attempt to delete a "tmp" file should never happen when `updated` is greater than 0. Does that make sense?

**Comment by advplyr** [comment]
Yeah it makes sense. I ran a few tests and have more data to complicate things. I added some logs in the `updateStoreData` method like so:
```js
    if (results.updated > 0) {
        console.log('Results were updated', tempstore, `Selected: ${results.selected} | Updated: ${results.updated}`)
        if (!await replaceFile(store, tempstore)) {
            results.errors = [...results.records];
            results.updated = 0;
        }
    } else {
        console.log('NO results updated', tempstore, `Selected: ${results.selected} | Updated: ${results.updated}`)
        await deleteFile(tempstore);
        console.log('File deleted', tempstore)
    }
```

In audiobookshelf when a user connects to the server it updates a timestamp on the user and saves, so to test I refreshed the browser about 15 times and caught the exception 3 times.

First, here is what the successful refresh looked like:
```
NO results updated C:\audiobookshelf\config\users\tmp\data.1.json.1643147254996.tmp Selected: 0 | Updated: 0
File deleted C:\audiobookshelf\config\users\tmp\data.1.json.1643147254996.tmp
Results were updated C:\audiobookshelf\config\users\tmp\data.3.json.1643147254996.tmp Selected: 1 | Updated: 1
[2022-01-25T21:47:35.027Z] DEBUG: [DB] Updated user: 1 | Selected: 1
```

The first exception was with the rename. This happened 2 of 15 refreshes.
```bash
NO results updated C:\audiobookshelf\config\users\tmp\data.1.json.1643147233538.tmp Selected: 0 | Updated: 0
File deleted C:\audiobookshelf\config\users\tmp\data.1.json.1643147233538.tmp
Results were updated C:\audiobookshelf\config\users\tmp\data.3.json.1643147233538.tmp Selected: 1 | Updated: 1
[Error: ENOENT: no such file or directory, rename 'C:\audiobookshelf\config\users\tmp\data.3.json.1643147233538.tmp' -> 'C:\audiobookshelf\config\users\data\data.3.json'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'rename',
  path: 'C:\\audiobookshelf\\config\\users\\tmp\\data.3.json.1643147233538.tmp',
  dest: 'C:\\audiobookshelf\\config\\users\\data\\data.3.json'
}
[2022-01-25T21:47:13.578Z] DEBUG: [DB] Updated user: 0 | Selected: 1
```

This is the same one I showed before, but now we can see that the data was updated in datastore 3 successfully, which is why it was showing 1 updated.
```bash
NO results updated C:\audiobookshelf\config\users\tmp\data.1.json.1643147306904.tmp Selected: 0 | Updated: 0
[Error: ENOENT: no such file or directory, unlink 'C:\audiobookshelf\config\users\tmp\data.1.json.1643147306904.tmp'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'unlink',
  path: 'C:\\audiobookshelf\\config\\users\\tmp\\data.1.json.1643147306904.tmp'
}
File deleted C:\audiobookshelf\config\users\tmp\data.1.json.1643147306904.tmp
Results were updated C:\audiobookshelf\config\users\tmp\data.3.json.1643147306904.tmp Selected: 1 | Updated: 1
[2022-01-25T21:48:26.965Z] DEBUG: [DB] Updated user: 1 | Selected: 1
```

**Comment by jamesbontempo** [comment]
I was actually in the middle of adding the `tempstore` path to the `results` object so you could essentially get the same info during testing :)

So, it seems we're back to node (or libuv) thinking that the tmp file doesn't exist. In all 3 cases, can you confirm that the tmp file actually _does_ exist? I know you've done this before, but I just want to double-check 👍

I guess at the very least, while we (continue to) try to track down the source of the file system errors, you can handle them in some way using the `selected` and `updated` values. In the case where `selected` != `updated` you can attempt to update the data again, and if `selected` == `updated` then you can ignore the error, confident that the necessary updates actually happened.

**Comment by jamesbontempo** [comment]
That logging was really helpful, BTW! 🙏

**Comment by jamesbontempo** [comment]
FYI, I just pushed an update that explicitly waits for the `writer` stream to open before attempting to write anything to it (for updates or deletes) based on [this Stack Overflow post](https://stackoverflow.com/questions/12906694/fs-createwritestream-does-not-immediately-create-file). I don't know if that will ensure that the tmp file gets created before throwing an error, but I figured it was worth a shot. Can you update `njodb` & see if the change makes a difference?

**Comment by advplyr** [comment]
I can confirm that the tmp file is actually being created.

I had to revert back to v0.4.29 because the settings db in audiobookshelf was not updating and showing 0 selected. I haven't had a chance to debug this, but the other db's were working fine.
Reverting to previous version resolved it.

**Comment by jamesbontempo** [comment]
Hey @advplyr!

I recently wandered back to making some updates to `njodb` and, at the same time, someone submitted an issue related to records not being updated. Their issue wasn't exactly what you were experiencing, but I do find myself wondering if the updates might help you out, too. In particular, it's related to one of the last changes I referenced here in this thread:

> FYI, I just pushed an update that explicitly waits for the `writer` stream to open before attempting to write anything to it (for updates or deletes) based on [this Stack Overflow post](https://stackoverflow.com/questions/12906694/fs-createwritestream-does-not-immediately-create-file). I don't know if that will ensure that the tmp file gets created before throwing an error, but I figured it was worth a shot.

Basically, what I just did was move _all_ the `reader`-related code into the `writer` "open" event block. In this way, `njodb` doesn't even try to open any data files to find matching records to update (or delete) until the `writer` is open.

Again, I'm not sure this will address the issue you were having, too, but If you're still using `njodb`, would you be willing to try upgrading to the new version (0.4.37) & seeing if that makes a difference?

Cheers,
James

**Comment by jamesbontempo** [comment]
Actually, I just checked audiobookshelf and it looks like you've migrated to sqlite 👍 Given that I've made the changes I mention above & haven't been able to replicate this issue locally, & also the fact that I'm working on a new version that natively handles file-locking, I'm going to close this issue.

**Comment by advplyr** [comment]
Hey, before Abs switched to sqlite I believe I resolved this issue for the copy of njodb Abs was using. Thanks for following up!
